# Generated by Django 4.0.5 on 2022-06-21 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participients',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
