# Generated by Django 4.0.5 on 2022-06-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participients',
            new_name='participants',
        ),
    ]
